name: fic17
description: Flutter Intensive Club batch 12.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  http: ^1.3.0
  intl: ^0.19.0
  mobile_scanner: ^5.1.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  timer_count_down: ^2.2.2
  win32: ^5.5.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_bloc: ^9.1.0
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/payment/
    - assets/icons/settings/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
